import { ICache, cache } from './cache/cache';
import { imgproc } from './imgproc/imgproc';
import { linalg } from './linalg/linalg';
import { math } from './math/math';
import matmath from './matmath/matmath';
import { matrix_t } from './matrix_t/matrix_t';
import { pyramid_t } from './pyramid_t/pyramid_t';
import { keypoint_t } from './keypoint_t/keypoint_t';
import { yape } from './yape/yape';
export default class jsfeatNext {
    private dt;
    protected cache: ICache;
    static cache: typeof cache;
    static imgproc: typeof imgproc;
    static linalg: typeof linalg;
    static math: typeof math;
    static matmath: typeof matmath;
    static matrix_t: typeof matrix_t;
    static pyramid_t: typeof pyramid_t;
    static keypoint_t: typeof keypoint_t;
    static yape: typeof yape;
    constructor();
    static VERSION: string;
    static EPSILON: number;
    static FLT_MIN: number;
    static U8_t: number;
    static S32_t: number;
    static F32_t: number;
    static S64_t: number;
    static F64_t: number;
    static C1_t: number;
    static C2_t: number;
    static C3_t: number;
    static C4_t: number;
    static COLOR_RGBA2GRAY: number;
    static COLOR_RGB2GRAY: number;
    static COLOR_BGRA2GRAY: number;
    static COLOR_BGR2GRAY: number;
    static BOX_BLUR_NOSCALE: number;
    static SVD_U_T: number;
    static SVD_V_T: number;
    static U8C1_t: number;
    static U8C3_t: number;
    static U8C4_t: number;
    static F32C1_t: number;
    static F32C2_t: number;
    static S32C1_t: number;
    static S32C2_t: number;
    get_data_type(type: number): number;
    get_channel(type: number): number;
    get_data_type_size(type: number): number;
}
